import Head from "next/head";
import React from "react";
import Layout from "../../components/Layout";

const Year: React.FC = () => {
  return (
    <>
      <Head>
        <title>Beat The Backlog!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>ETT GÖTT ÅR</h1>
      </Layout>
    </>
  );
};

export default Year;
