import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout";

const Finished: NextPage = () => {
  return (
    <>
      <Head>
        <title>Beat The Backlog!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
          <h1>Finished</h1>
      </Layout>
    </>
  );
};

export default Finished;
